#!/bin/bash

alias s='git status'
alias a='git add'
alias rc='git rebase --continue'
alias ri='git rebase -i'
alias c='git commit'
alias ca='git commit --all'
alias cn='git commit --amend'
alias cne='git commit --amend --no-edit'
alias cna='git commit --all --amend'
alias cnae='git commit --all --amend --no-edit'
alias l='git log'
alias d='git diff'
alias ds='git diff --stat'
alias dc='git diff --cached'
alias dcs='git diff --cached --stat'
alias sw='git show'
alias sws='git show --stat'
alias b='git branch'
alias ch='git checkout'
alias rs='git reset'
alias rsh='git reset --hard'
alias rl='git reflog'
alias f='git fetch'
alias p='git push -u origin HEAD'
